export const USER_SELECTED = "USER_SELECTED";
export const USERS_RECEIVED = "USERS_RECEIVED";
export const REQUEST_USERS_FAILED = "REQUEST_USERS_FAILED";
export const REQUEST_USERS = "REQUEST_USERS";
